In [3]:
import torch

def get_att_mask(qt, kt):
        '''
        generate attention mask to avoid seeing future events at reference points t.

        inputs:
            qt: reference points, shape (B, R)
            kt: time steps, shape (B, L)

        output: 
            tril matrix, shape (B, R, L)
        '''
        return (qt.unsqueeze(2) >= kt.unsqueeze(1)).int()  # Shape: [B, nq, nk]

qt = torch.tensor([[2, 5], [4, 7]])
kt = torch.tensor([[0, 3], [1, 2]])
get_att_mask(qt, kt)

tensor([[[1, 0],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int32)

In [1]:
import numpy as np
import os

from Cluster.metrics import get_cls_scores_from_label, get_cls_scores_without_label

x_corpus = np.load('./temp_model/[RD74--TE__pp_single_mark-concat-d1]/data/x_corpus.npz')['arr_0']
cluster = np.load('./temp_model/[RD74--TE__pp_single_mark-concat-d1]/data/cluster.npz')['arr_0']
label = np.load('./temp_model/[RD74--TE__pp_single_mark-concat-d1]/data/label.npz')['arr_0']

In [2]:
get_cls_scores_from_label(label, cluster)

{'PURITY': 0.8778730535406295,
 'RAND': 0.012137789392783767,
 'MI': 0.01624738064920259}

In [17]:
import numpy as np
seq_len = 3
seq_num = 16
subsequent_mask = np.tile(np.triu(np.ones((seq_len, seq_len), dtype=bool), k=0)[None, :, :], (seq_num, 1, 1))
subsequent_mask.shape

(16, 3, 3)

In [6]:
import numpy as np
list(np.zeros([1, 3] + [4]).shape[:-1]) + [4]

[1, 3, 4]

In [15]:
subsequent_mask[:, :, [0]]

array([[[ True],
        [False],
        [False]],

       [[ True],
        [False],
        [False]],

       [[ True],
        [False],
        [False]]])

In [16]:
subsequent_mask * subsequent_mask[:, :, [0]]

array([[[ True,  True,  True],
        [False, False, False],
        [False, False, False]],

       [[ True,  True,  True],
        [False, False, False],
        [False, False, False]],

       [[ True,  True,  True],
        [False, False, False],
        [False, False, False]]])

In [ ]:
import pickle

with open("dataset/p12-raindrop/split0/test_state.pkl", "rb") as f:
    original = pickle.load(f)

dict_keys(['hospital', 'num_states', 'state', 'dict_map_states', 'num_demos', 'demo', 'dict_map_demos'])

In [21]:
len(set(list(a['hospital'].keys())).union(set(list(b['hospital'].keys()))))

2262

In [31]:
a['dict_map_demos']

{'Age': 0,
 'Gender': 1,
 'Height': 2,
 'ICUType0': 3,
 'ICUType1': 4,
 'ICUType2': 5,
 'ICUType3': 6}

In [28]:
type(a['state'])

list